// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package icons

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Docker() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"brand-icon-block\" title=\"Docker\"><svg class=\"w-12\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 15 15\"><path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M9 1H6v2H2v2H0v3.5A5.5 5.5 0 0 0 5.5 14h.528a7.736 7.736 0 0 0 6.774-4H15V8.5A1.5 1.5 0 0 0 13.5 7H13v-.5A1.5 1.5 0 0 0 11.5 5H9V1ZM1 7h1V6H1v1Zm2 0h1V6H3v1Zm2 0h1V6H5v1Zm2 0h1V6H7v1Zm2 0h1V6H9v1ZM8 3V2H7v1h1ZM6 4H5v1h1V4Zm1 1V4h1v1H7ZM4 5V4H3v1h1Zm-1 5h1V9H3v1Z\" clip-rule=\"evenodd\"></path></svg></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
