// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package lockups

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Afk() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"mt-6 mb-2\"><h2 class=\"uppercase font-bold text-3xl\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `AFK`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h2><p class=\"mt-2 mb-3\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := `"You gotta walk the dog" --someone wise`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em></p><p class=\"my-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `These are my favorite ways to rest and recharge away from keyboard.`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div><div class=\"mt-2 mb-6\"><div class=\"my-2 flex items-center\" title=\"Family Time\" aria-label=\"Family Time\"><svg width=\"24\" height=\"24\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\"><path fill=\"currentColor\" d=\"M18 6q-.825 0-1.412-.587T16 4q0-.825.588-1.412T18 2q.825 0 1.413.588T20 4q0 .825-.587 1.413T18 6m-1 16v-8q0-1-.513-1.8t-1.312-1.25l.875-2.575q.2-.625.738-1T18 7q.675 0 1.213.375t.737 1L22.5 16H20v6zm-4.5-10.5q-.625 0-1.062-.437T11 10q0-.625.438-1.062T12.5 8.5q.625 0 1.063.438T14 10q0 .625-.437 1.063T12.5 11.5M5.5 6q-.825 0-1.412-.587T3.5 4q0-.825.588-1.412T5.5 2q.825 0 1.413.588T7.5 4q0 .825-.587 1.413T5.5 6m-2 16v-7H2V9q0-.825.588-1.412T4 7h3q.825 0 1.413.588T9 9v6H7.5v7zm7.5 0v-4h-1v-4q0-.625.438-1.062T11.5 12.5h2q.625 0 1.063.438T15 14v4h-1v4z\"></path></svg><p class=\"ml-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var5 := `Spending time with family`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div><div class=\"my-2 flex items-center\" title=\"Horsemanship\" aria-label=\"Horsemanship\"><svg width=\"24\" height=\"24\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\"><path fill=\"currentColor\" d=\"M22 6v3.5l-1.5.5l-1.54-2.46c-.13-.21-.46-.12-.46.13v3.58c0 .98-.39 1.86-1 2.53V21H15v-6h-.25c-.21 0-.42-.03-.62-.06l-4.44-.74l-1.12 2.01l.96 4.79H7l-1-4.75c-.03-.3 0-.6.16-.86l1.02-1.81a3.272 3.272 0 0 1-1.68-2.77c-.04.15-.06.37-.03.69c.03.44.14 1.09.07 1.81c-.04.72-.37 1.46-.79 1.95c-.43.49-.9.83-1.4 1.09l-.7-.7c.19-.47.38-.89.42-1.28c.06-.37-.01-.67-.12-.94l-.53-1.13c-.21-.51-.47-1.25-.42-2.12c.03-.85.5-1.96 1.39-2.57c.9-.61 1.87-.69 2.66-.53c.5.1 1.01.34 1.45.68c.37-.17.8-.26 1.25-.26h5.75V7c0-2.21 1.79-4 4-4H22l-.89 1.34c.54.36.89.97.89 1.66\"></path></svg><p class=\"ml-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := `Riding and training our horses`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div><div class=\"my-2 flex items-center\" title=\"BBQ\" aria-label=\"BBQ\"><svg width=\"24\" height=\"24\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 11 11\"><path d=\"M4 1.75s0-1 1-1c0 0 .5 0 .5-.5a.25.25 0 1 1 .5 0s0 1-1 1c0 0-.5 0-.5.5a.25.25 0 1 1-.5 0zM2.25 2a.25.25 0 0 0 .25-.25c0-.5.5-.5.5-.5c1 0 1-1 1-1a.25.25 0 1 0-.5 0c0 .5-.5.5-.5.5c-1 0-1 1-1 1c0 .138.112.25.25.25zm4 0a.25.25 0 0 0 .25-.25c0-.5.5-.5.5-.5c1 0 1-1 1-1a.25.25 0 1 0-.5 0c0 .5-.5.5-.5.5c-1 0-1 1-1 1c0 .138.112.25.25.25zm3.5-2a.25.25 0 0 0-.25.25c0 .5-.5.5-.5.5c-1 0-1 1-1 1a.25.25 0 1 0 .5 0c0-.5.5-.5.5-.5c1 0 1-1 1-1A.25.25 0 0 0 9.75 0zM6.675 5.865l-.001.001l2.3 4.782v.009a.242.242 0 0 1-.12.32a.247.247 0 0 1-.328-.12L7.845 9.5H4a1.5 1.5 0 1 1-.91-1.379c.053.02.105.045.155.072L4.278 5.85A3.038 3.038 0 0 1 2 3h7s-.002 2.282-2.325 2.865zM3.25 9.5a.75.75 0 1 0-1.5 0a.75.75 0 0 0 1.5 0zm2.923-3.544C5.963 5.983 5.742 6 5.5 6c-.285 0-.713-.047-.713-.047l-1.144 2.58c.123.136.218.295.279.467h3.673L6.173 5.956z\" fill=\"currentColor\"></path></svg><p class=\"ml-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var7 := `Cooking with fire outdoors`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
