// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package lockups

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Certifications() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"mt-8\"><h2 class=\"uppercase font-bold text-3xl\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `Certifications`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h2></div><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := ` CKA `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><div class=\"flex items-center\"><a href=\"https://www.credly.com/badges/fb5cbf16-55bc-438b-9983-578841304de5/public_url\" target=\"_blank\"><div class=\"flex items-center justify-start\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" viewBox=\"0 0 256 256\"><path fill=\"currentColor\" d=\"M248 128a52 52 0 1 0-92 33.19V220a12 12 0 0 0 18 10.42l22-12.6l22.05 12.6A12 12 0 0 0 236 220v-58.81A51.77 51.77 0 0 0 248 128m-52-28a28 28 0 1 1-28 28a28 28 0 0 1 28-28m6 93.58a12 12 0 0 0-11.9 0l-10.1 5.74v-21.85a51.86 51.86 0 0 0 32 0v21.85ZM140 192a12 12 0 0 1-12 12H40a20 20 0 0 1-20-20V56a20 20 0 0 1 20-20h176a20 20 0 0 1 20 20a12 12 0 0 1-23.32 4H44v120h84a12 12 0 0 1 12 12m-12-52a12 12 0 0 1-12 12H76a12 12 0 0 1 0-24h40a12 12 0 0 1 12 12m0-40a12 12 0 0 1-12 12H76a12 12 0 0 1 0-24h40a12 12 0 0 1 12 12\"></path></svg> <span class=\"ml-2 my-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `Certified Kubernetes Administrator`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></div></a></div><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var5 := ` GCP ACE `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><div class=\"flex items-center\"><a href=\"https://www.credly.com/badges/93f52a6f-2425-4d88-b952-d45f9fbf475e/public_url\" target=\"_blank\"><div class=\"flex items-center justify-start\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" viewBox=\"0 0 256 256\"><path fill=\"currentColor\" d=\"M248 128a52 52 0 1 0-92 33.19V220a12 12 0 0 0 18 10.42l22-12.6l22.05 12.6A12 12 0 0 0 236 220v-58.81A51.77 51.77 0 0 0 248 128m-52-28a28 28 0 1 1-28 28a28 28 0 0 1 28-28m6 93.58a12 12 0 0 0-11.9 0l-10.1 5.74v-21.85a51.86 51.86 0 0 0 32 0v21.85ZM140 192a12 12 0 0 1-12 12H40a20 20 0 0 1-20-20V56a20 20 0 0 1 20-20h176a20 20 0 0 1 20 20a12 12 0 0 1-23.32 4H44v120h84a12 12 0 0 1 12 12m-12-52a12 12 0 0 1-12 12H76a12 12 0 0 1 0-24h40a12 12 0 0 1 12 12m0-40a12 12 0 0 1-12 12H76a12 12 0 0 1 0-24h40a12 12 0 0 1 12 12\"></path></svg> <span class=\"ml-2 my-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := `Google Certified Associate Cloud Engineer`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></div></a></div><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var7 := ` Terraform Associate `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><a href=\"https://www.credly.com/badges/15035634-0643-4d71-8ec6-0fccbd9864a7/public_url\" target=\"_blank\"><div class=\"flex items-center justify-start\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" viewBox=\"0 0 256 256\"><path fill=\"currentColor\" d=\"M248 128a52 52 0 1 0-92 33.19V220a12 12 0 0 0 18 10.42l22-12.6l22.05 12.6A12 12 0 0 0 236 220v-58.81A51.77 51.77 0 0 0 248 128m-52-28a28 28 0 1 1-28 28a28 28 0 0 1 28-28m6 93.58a12 12 0 0 0-11.9 0l-10.1 5.74v-21.85a51.86 51.86 0 0 0 32 0v21.85ZM140 192a12 12 0 0 1-12 12H40a20 20 0 0 1-20-20V56a20 20 0 0 1 20-20h176a20 20 0 0 1 20 20a12 12 0 0 1-23.32 4H44v120h84a12 12 0 0 1 12 12m-12-52a12 12 0 0 1-12 12H76a12 12 0 0 1 0-24h40a12 12 0 0 1 12 12m0-40a12 12 0 0 1-12 12H76a12 12 0 0 1 0-24h40a12 12 0 0 1 12 12\"></path></svg> <span class=\"ml-2 my-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var8 := `HashiCorp Certified Terraform Associate`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></div></a>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
